#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HELPER_PATH="$ROOT_DIR/scripts/configure-samsar-custom-image-model.mjs"
ADAPTER_FILE="${SAMSAR_CUSTOM_IMAGE_ADAPTER_FILE:-$HOME/.config/samsar/vast-flux2/latest.adapter.json}"
PROCESSOR_CONTAINER="${SAMSAR_PROCESSOR_CONTAINER:-samsar-processor-1}"
USER_EMAIL="${SAMSAR_USER_EMAIL:-}"
ADAPTER_ID="${SAMSAR_CUSTOM_IMAGE_ADAPTER_ID:-vast_flux2_klein_4b}"
SET_AGENT_DEFAULT="1"

usage() {
  cat <<'EOF'
Usage: ./configure-samsar-custom-image-model.sh [options]

Configure a provisioned custom text-to-image adapter for a local standalone
Samsar user. The adapter is made available in Studio and VidGenie and becomes
the Agent's default image model.

Options:
  --adapter-file PATH       Secure adapter JSON generated by the Vast provisioner
  --user-email EMAIL       Target this user instead of auto-selecting the standalone admin
  --container NAME         Processor container name (default: samsar-processor-1)
  --adapter-id ID          Stable custom adapter ID (default: vast_flux2_klein_4b)
  --no-agent-default       Save the model without changing the Agent default
  -h, --help               Show this help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --adapter-file)
      [[ $# -ge 2 ]] || { echo "--adapter-file requires a path" >&2; exit 2; }
      ADAPTER_FILE="$2"
      shift 2
      ;;
    --user-email)
      [[ $# -ge 2 ]] || { echo "--user-email requires an email" >&2; exit 2; }
      USER_EMAIL="$2"
      shift 2
      ;;
    --container)
      [[ $# -ge 2 ]] || { echo "--container requires a name" >&2; exit 2; }
      PROCESSOR_CONTAINER="$2"
      shift 2
      ;;
    --adapter-id)
      [[ $# -ge 2 ]] || { echo "--adapter-id requires an ID" >&2; exit 2; }
      ADAPTER_ID="$2"
      shift 2
      ;;
    --no-agent-default)
      SET_AGENT_DEFAULT="0"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ ! -f "$ADAPTER_FILE" ]]; then
  echo "Adapter file not found: $ADAPTER_FILE" >&2
  echo "Provision FLUX.2 first or pass --adapter-file explicitly." >&2
  exit 1
fi

if [[ ! -f "$HELPER_PATH" ]]; then
  echo "Samsar configuration helper not found: $HELPER_PATH" >&2
  exit 1
fi

if [[ ! "$ADAPTER_ID" =~ ^[A-Za-z0-9._-]+$ ]]; then
  echo "--adapter-id may contain only letters, numbers, dots, underscores, and hyphens" >&2
  exit 2
fi

if ! docker inspect "$PROCESSOR_CONTAINER" >/dev/null 2>&1; then
  echo "Processor container not found: $PROCESSOR_CONTAINER" >&2
  exit 1
fi

if [[ "$(docker inspect -f '{{.State.Running}}' "$PROCESSOR_CONTAINER")" != "true" ]]; then
  echo "Processor container is not running: $PROCESSOR_CONTAINER" >&2
  exit 1
fi

REMOTE_SUFFIX="$$"
REMOTE_HELPER="/tmp/samsar-configure-custom-image-${REMOTE_SUFFIX}.mjs"
REMOTE_ADAPTER="/tmp/samsar-custom-image-adapter-${REMOTE_SUFFIX}.json"

cleanup() {
  docker exec "$PROCESSOR_CONTAINER" rm -f "$REMOTE_HELPER" "$REMOTE_ADAPTER" >/dev/null 2>&1 || true
}
trap cleanup EXIT

docker cp "$HELPER_PATH" "$PROCESSOR_CONTAINER:$REMOTE_HELPER" >/dev/null
docker cp "$ADAPTER_FILE" "$PROCESSOR_CONTAINER:$REMOTE_ADAPTER" >/dev/null

COMMAND=(
  docker exec
  -e "SAMSAR_CUSTOM_IMAGE_ADAPTER_ID=$ADAPTER_ID"
  -e "SAMSAR_SET_AGENT_IMAGE_DEFAULT=$SET_AGENT_DEFAULT"
  "$PROCESSOR_CONTAINER"
  node
  "$REMOTE_HELPER"
  "$REMOTE_ADAPTER"
)
if [[ -n "$USER_EMAIL" ]]; then
  COMMAND+=(--user-email "$USER_EMAIL")
fi

"${COMMAND[@]}"

echo "Reload the Samsar browser tab to refresh the user model list."
