import { EXPRESS_VIDEO_CREDITS_PER_SECOND_BY_MODEL } from './pricing/ExpressVideoPricingDistribution.js';

export const EXPRESS_VIDEO_IMAGE_MODEL_KEYS = Object.freeze([
  'GPTIMAGE2',
  'NANOBANANA2',
  'NANOBANANAPRO',
  'SEEDREAM',
]);

export const EXPRESS_VIDEO_VIDEO_MODEL_KEYS = Object.freeze(
  Object.keys(EXPRESS_VIDEO_CREDITS_PER_SECOND_BY_MODEL),
);

export const TEXT_TO_VIDEO_IMAGE_MODEL_KEYS = EXPRESS_VIDEO_IMAGE_MODEL_KEYS;
export const TEXT_TO_VIDEO_VIDEO_MODEL_KEYS = EXPRESS_VIDEO_VIDEO_MODEL_KEYS;
export const IMAGE_LIST_TO_VIDEO_IMAGE_MODEL_KEYS = EXPRESS_VIDEO_IMAGE_MODEL_KEYS;
export const IMAGE_LIST_TO_VIDEO_VIDEO_MODEL_KEYS = EXPRESS_VIDEO_VIDEO_MODEL_KEYS;
