export const SCENE_ACTION_COMMAND = '/scene_actions';

export const SCENE_ACTIONS = [
  {
    id: 'fade_to_black',
    label: 'Fade to black',
    category: 'Fades',
    description: 'Adds a full-canvas black overlay that fades from transparent to opaque.',
    operation: { type: 'overlayFade', color: '#000000', startFade: 0, endFade: 100 },
  },
  {
    id: 'fade_from_black',
    label: 'Fade from black',
    category: 'Fades',
    description: 'Starts with a black overlay and fades it out to reveal the layer.',
    operation: { type: 'overlayFade', color: '#000000', startFade: 100, endFade: 0 },
  },
  {
    id: 'fade_to_white',
    label: 'Fade to white',
    category: 'Fades',
    description: 'Adds a full-canvas white overlay that fades from transparent to opaque.',
    operation: { type: 'overlayFade', color: '#ffffff', startFade: 0, endFade: 100 },
  },
  {
    id: 'fade_from_white',
    label: 'Fade from white',
    category: 'Fades',
    description: 'Starts with a white overlay and fades it out to reveal the layer.',
    operation: { type: 'overlayFade', color: '#ffffff', startFade: 100, endFade: 0 },
  },
  {
    id: 'dim_scene',
    label: 'Dim scene',
    category: 'Fades',
    description: 'Adds a black overlay that gently dims the layer.',
    operation: { type: 'overlayFade', color: '#000000', startFade: 0, endFade: 45 },
  },
  {
    id: 'layer_fade_in',
    label: 'Layer fade in',
    category: 'Fades',
    description: 'Fades existing visual items from transparent to opaque.',
    operation: { type: 'itemFade', startFade: 0, endFade: 100 },
  },
  {
    id: 'layer_fade_out',
    label: 'Layer fade out',
    category: 'Fades',
    description: 'Fades existing visual items from opaque to transparent.',
    operation: { type: 'itemFade', startFade: 100, endFade: 0 },
  },
  {
    id: 'wipe_to_black_right',
    label: 'Wipe to black right',
    category: 'Wipes',
    description: 'Slides a black full-canvas rectangle in from the left.',
    operation: { type: 'overlayWipe', color: '#000000', mode: 'cover', direction: 'right' },
  },
  {
    id: 'wipe_to_black_left',
    label: 'Wipe to black left',
    category: 'Wipes',
    description: 'Slides a black full-canvas rectangle in from the right.',
    operation: { type: 'overlayWipe', color: '#000000', mode: 'cover', direction: 'left' },
  },
  {
    id: 'wipe_to_black_down',
    label: 'Wipe to black down',
    category: 'Wipes',
    description: 'Slides a black full-canvas rectangle in from the top.',
    operation: { type: 'overlayWipe', color: '#000000', mode: 'cover', direction: 'down' },
  },
  {
    id: 'wipe_to_black_up',
    label: 'Wipe to black up',
    category: 'Wipes',
    description: 'Slides a black full-canvas rectangle in from the bottom.',
    operation: { type: 'overlayWipe', color: '#000000', mode: 'cover', direction: 'up' },
  },
  {
    id: 'reveal_from_black_right',
    label: 'Reveal from black right',
    category: 'Wipes',
    description: 'Starts covered in black and slides the cover out to the right.',
    operation: { type: 'overlayWipe', color: '#000000', mode: 'reveal', direction: 'right' },
  },
  {
    id: 'reveal_from_black_left',
    label: 'Reveal from black left',
    category: 'Wipes',
    description: 'Starts covered in black and slides the cover out to the left.',
    operation: { type: 'overlayWipe', color: '#000000', mode: 'reveal', direction: 'left' },
  },
  {
    id: 'letterbox_in',
    label: 'Letterbox in',
    category: 'Cinematic',
    description: 'Slides black bars in from the top and bottom edges.',
    operation: { type: 'letterbox', mode: 'in' },
  },
  {
    id: 'letterbox_out',
    label: 'Letterbox out',
    category: 'Cinematic',
    description: 'Slides black bars out toward the top and bottom edges.',
    operation: { type: 'letterbox', mode: 'out' },
  },
  {
    id: 'slow_zoom_in',
    label: 'Slow zoom in',
    category: 'Camera',
    description: 'Applies a gentle zoom-in to image items.',
    operation: { type: 'imageZoom', startScale: 100, endScale: 112 },
  },
  {
    id: 'slow_zoom_out',
    label: 'Slow zoom out',
    category: 'Camera',
    description: 'Applies a gentle zoom-out to image items.',
    operation: { type: 'imageZoom', startScale: 112, endScale: 100 },
  },
  {
    id: 'punch_in',
    label: 'Punch in',
    category: 'Camera',
    description: 'Applies a stronger push-in zoom to image items.',
    operation: { type: 'imageZoom', startScale: 100, endScale: 130 },
  },
  {
    id: 'pan_right',
    label: 'Pan right',
    category: 'Camera',
    description: 'Slides image items slightly to the right across the layer duration.',
    operation: { type: 'imageSlideDelta', deltaXRatio: 0.08, deltaYRatio: 0 },
  },
  {
    id: 'pan_left',
    label: 'Pan left',
    category: 'Camera',
    description: 'Slides image items slightly to the left across the layer duration.',
    operation: { type: 'imageSlideDelta', deltaXRatio: -0.08, deltaYRatio: 0 },
  },
  {
    id: 'pan_up',
    label: 'Pan up',
    category: 'Camera',
    description: 'Slides image items slightly upward across the layer duration.',
    operation: { type: 'imageSlideDelta', deltaXRatio: 0, deltaYRatio: -0.08 },
  },
  {
    id: 'pan_down',
    label: 'Pan down',
    category: 'Camera',
    description: 'Slides image items slightly downward across the layer duration.',
    operation: { type: 'imageSlideDelta', deltaXRatio: 0, deltaYRatio: 0.08 },
  },
  {
    id: 'zoom_slide_right',
    label: 'Zoom and slide right',
    category: 'Camera',
    description: 'Combines a zoom-in with a rightward slide on image items.',
    operation: { type: 'imageZoomSlide', startScale: 100, endScale: 115, deltaXRatio: 0.08, deltaYRatio: 0 },
  },
  {
    id: 'zoom_slide_left',
    label: 'Zoom and slide left',
    category: 'Camera',
    description: 'Combines a zoom-in with a leftward slide on image items.',
    operation: { type: 'imageZoomSlide', startScale: 100, endScale: 115, deltaXRatio: -0.08, deltaYRatio: 0 },
  },
  {
    id: 'slide_in_from_right',
    label: 'Slide in from right',
    category: 'Entrances',
    description: 'Slides image items from the right edge into their current position.',
    operation: { type: 'imageSlideIn', direction: 'right' },
  },
  {
    id: 'slide_in_from_left',
    label: 'Slide in from left',
    category: 'Entrances',
    description: 'Slides image items from the left edge into their current position.',
    operation: { type: 'imageSlideIn', direction: 'left' },
  },
  {
    id: 'slide_out_to_right',
    label: 'Slide out to right',
    category: 'Exits',
    description: 'Slides image items out toward the right edge.',
    operation: { type: 'imageSlideOut', direction: 'right' },
  },
  {
    id: 'slide_out_to_left',
    label: 'Slide out to left',
    category: 'Exits',
    description: 'Slides image items out toward the left edge.',
    operation: { type: 'imageSlideOut', direction: 'left' },
  },
  {
    id: 'gentle_sway',
    label: 'Gentle sway',
    category: 'Motion',
    description: 'Adds a subtle horizontal sway to image items.',
    operation: { type: 'imageSway', amplitude: 24, frequency: 0.3 },
  },
];

export function getSceneActionById(actionId) {
  return SCENE_ACTIONS.find((action) => action.id === actionId) || null;
}

export function getSceneActionSummaries() {
  return SCENE_ACTIONS.map(({ id, label, category, description }) => ({
    id,
    label,
    category,
    description,
  }));
}
