export const PLAY_SPEECH_LIST = [
  {
    "label": "Angelo",
    "accent": "us",
    "gender": "m",
    "age": "young",
    "style": "conversational",
    "voice name": "dialog angelo",
    "value": "s3://voice-cloning-zero-shot/baf1ef41-36b6-428c-9bdf-50ba54682bd8/original/manifest.json",
    "provider": "PLAYAI",
    "previewURL": "https://peregrine-samples.s3.us-east-1.amazonaws.com/parrot-samples/Angelo_Sample.wav"
  },
  {
    "label": "Deedee",
    "accent": "us african american",
    "gender": "f",
    "age": "middle",
    "style": "conversational",
    "voice name": "dialog deedee",
    "value": "s3://voice-cloning-zero-shot/e040bd1b-f190-4bdb-83f0-75ef85b18f84/original/manifest.json",
    "provider": "PLAYAI",
    "previewURL": "https://peregrine-samples.s3.us-east-1.amazonaws.com/parrot-samples/Deedee_Sample.wav"
  },

  {
    "label": "Jennifer",
    "accent": "british (yorkshire)",
    "gender": "f",
    "age": "middle",
    "style": "conversational",
    "voice name": "dialog jennifer",
    "value": "s3://voice-cloning-zero-shot/801a663f-efd0-4254-98d0-5c175514c3e8/jennifer/manifest.json",
    "provider": "PLAYAI",
    "previewURL": "https://peregrine-samples.s3.amazonaws.com/parrot-samples/jennifer.wav"
  },


  {
    "label": "Briggs",
    "gender": "m",
    "style": "conversational",
    "voice name": "dialog briggs",
    "value": "s3://voice-cloning-zero-shot/71cdb799-1e03-41c6-8a05-f7cd55134b0b/original/manifest.json",
    "provider": "PLAYAI",
    "previewURL": "https://peregrine-samples.s3.us-east-1.amazonaws.com/parrot-samples/Briggs_Sample.wav"
  },


  {
    "label": "Samara",
    "gender": "f",
    "style": "conversational",
    "voice name": "dialog samara",
    "value": "s3://voice-cloning-zero-shot/90217770-a480-4a91-b1ea-df00f4d4c29d/original/manifest.json",
    "provider": "PLAYAI",
    "previewURL": "https://peregrine-samples.s3.us-east-1.amazonaws.com/parrot-samples/Samara_Sample.wav"
  },


  {
    "label": "Aaliyah",
    "gender": "f",
    "style": "conversational",
    "voice name": "dialog aaliyah",
    "value": "s3://voice-cloning-zero-shot/f6c4ed76-1b55-4cd9-8896-31f7535f6cdb/original/manifest.json",
    "provider": "PLAYAI",
    "previewURL": "https://peregrine-samples.s3.us-east-1.amazonaws.com/parrot-samples/Aaliyah_Sample.wav"
  },

  {
    "label": "Arsenio",
    "accent": "us african american",
    "gender": "m",
    "age": "middle",
    "style": "conversational",
    "voice name": "dialog arsenio",
    "value": "s3://voice-cloning-zero-shot/65977f5e-a22a-4b36-861b-ecede19bdd65/original/manifest.json",
    "provider": "PLAYAI",
    "previewURL": "https://peregrine-samples.s3.us-east-1.amazonaws.com/parrot-samples/Arsenio_Sample.wav"
  },

  {
    "label": "Timo",
    "accent": "us",
    "gender": "m",
    "age": "middle",
    "style": "conversational",
    "voice name": "dialog timo",
    "value": "s3://voice-cloning-zero-shot/677a4ae3-252f-476e-85ce-eeed68e85951/original/manifest.json",
    "provider": "PLAYAI",
    "previewURL": "https://peregrine-samples.s3.us-east-1.amazonaws.com/parrot-samples/Timo_Sample.wav"
  },
  {
    "label": "Dexter",
    "accent": "us",
    "gender": "m",
    "age": "middle",
    "style": "conversational",
    "voice name": "dialog dexter",
    "value": "s3://voice-cloning-zero-shot/b27bc13e-996f-4841-b584-4d35801aea98/original/manifest.json",
    "provider": "PLAYAI",
    "previewURL": "https://peregrine-samples.s3.us-east-1.amazonaws.com/parrot-samples/Dexter_Sample.wav"
  },
  {
    "label": "Briggs",
    "accent": "us southern (oklahoma)",
    "gender": "m",
    "age": "old",
    "style": "conversational",
    "voice name": "dialog briggs",
    "value": "s3://voice-cloning-zero-shot/71cdb799-1e03-41c6-8a05-f7cd55134b0b/original/manifest.json",
    "provider": "PLAYAI",
    "previewURL": "https://peregrine-samples.s3.us-east-1.amazonaws.com/parrot-samples/Briggs_Sample.wav"
  },

  {
    "label": "Nia",
    "accent": "us",
    "gender": "f",
    "age": "young",
    "style": "conversational",
    "voice name": "dialog nia",
    "value": "s3://voice-cloning-zero-shot/831bd330-85c6-4333-b2b4-10c476ea3491/original/manifest.json",
    "provider": "PLAYAI",
    "previewURL": "https://peregrine-samples.s3.us-east-1.amazonaws.com/parrot-samples/Nia_Sample.wav"
  },
  {
    "label": "Inara",
    "accent": "us african american",
    "gender": "f",
    "age": "middle",
    "style": "conversational",
    "voice name": "dialog inara",
    "value": "s3://voice-cloning-zero-shot/adb83b67-8d75-48ff-ad4d-a0840d231ef1/original/manifest.json",
    "provider": "PLAYAI",
    "previewURL": "https://peregrine-samples.s3.us-east-1.amazonaws.com/parrot-samples/Inara_Sample.wav"
  },

]



export const OPENAI_SPEAKER_TYPES = [
  { value: 'alloy', label: 'Alloy', provider: 'OPENAI' ,
    "Gender": "N",
  },
  { value: 'echo', label: 'Echo', provider: 'OPENAI',
    "Gender": "M",
   },
  { value: 'fable', label: 'Fable', provider: 'OPENAI',
    "Gender": "M",
   },
  { value: 'onyx', label: 'Onyx', provider: 'OPENAI',
    "Gender": "M",
   },
  { value: 'nova', label: 'Nova', provider: 'OPENAI' ,
    "Gender": "F",
  },
  { value: 'shimmer', label: 'Shimmer', provider: 'OPENAI',
    "Gender": "F",
   },
];


export const ELEVENLABS_SPEAKER_TYPES = [
  {
    voiceId: "gOupLcAkjEnguROwi4oS",
    value: "gOupLcAkjEnguROwi4oS",
    name: "Darian",
    label: "Darian - Warm Grounded Storyteller",
    gender: "male",
    age: "middle-aged",
    accent: "American",
    style: "deep",
    useCase: "advertisement",
    languageCode: "en",
    languageCodes: ["en", "uk", "zh", "it", "es", "tr", "ms", "id", "no", "cs", "vi", "ru", "de", "pt", "hi", "pl"],
    category: "high_quality",
    description: "Warm, grounded male baritone. Natural and confident for storytelling and brand reads.",
    previewURL: "https://storage.googleapis.com/eleven-public-prod/database/workspace/1da06ea679a54975ad96a2221fe6530d/voices/gOupLcAkjEnguROwi4oS/AyYfK0CnNPq37Rzj9jA3.mp3",
    provider: "ELEVENLABS",
  },
  {
    voiceId: "OZ0L6eISlOejga3XjDFt",
    value: "OZ0L6eISlOejga3XjDFt",
    name: "Talia",
    label: "Talia - Warm Soft Guide",
    gender: "female",
    age: "middle-aged",
    accent: "American",
    style: "pleasant",
    useCase: "informative_educational",
    languageCode: "en",
    languageCodes: ["en", "hr", "hu", "sv", "ta", "no", "cs", "fr", "pl", "vi", "ro", "uk", "ar", "tr", "ko", "es", "nl", "de", "pt"],
    category: "high_quality",
    description: "Warm female tone. Soft, caring, and relaxed for calm narration and supportive messages.",
    previewURL: "https://storage.googleapis.com/eleven-public-prod/database/workspace/1da06ea679a54975ad96a2221fe6530d/voices/OZ0L6eISlOejga3XjDFt/feNpPK3UmI71iHFkml8g.mp3",
    provider: "ELEVENLABS",
  },
  {
    voiceId: "WQP7cQUF5aAS6Axh5yaa",
    value: "WQP7cQUF5aAS6Axh5yaa",
    name: "Elara",
    label: "Elara - Crisp Pro Narrator",
    gender: "female",
    age: "middle-aged",
    accent: "American",
    style: "pleasant",
    useCase: "narrative_story",
    languageCode: "en",
    languageCodes: ["en", "el", "id", "ms", "no", "bg", "hr", "ta", "zh", "it", "uk", "es", "nl", "tr", "ru", "de", "pt"],
    category: "high_quality",
    description: "Clean, bright female tone. Polished and clear for professional narration and product demos.",
    previewURL: "https://storage.googleapis.com/eleven-public-prod/database/workspace/1da06ea679a54975ad96a2221fe6530d/voices/WQP7cQUF5aAS6Axh5yaa/bG5JpSVsfxR6bgeyRnzk.mp3",
    provider: "ELEVENLABS",
  },
  {
    voiceId: "jSuBIjxMKhqIfb0wCK1F",
    value: "jSuBIjxMKhqIfb0wCK1F",
    name: "Baxter",
    label: "Baxter - Dry Calm Aussie",
    gender: "male",
    age: "young",
    accent: "Australian",
    style: "deep",
    useCase: "narrative_story",
    languageCode: "en",
    languageCodes: ["en", "it", "ar", "es", "tr", "ms", "nl", "id", "ko", "fr", "no", "el", "vi", "ta", "ru", "hu", "de", "pt", "hi", "pl"],
    category: "high_quality",
    description: "Medium low male tone with an Australian/New Zealand accent. Grounded and steady for documentary style narration.",
    previewURL: "https://storage.googleapis.com/eleven-public-prod/database/workspace/1da06ea679a54975ad96a2221fe6530d/voices/jSuBIjxMKhqIfb0wCK1F/b303c261-17fd-43e3-bd67-96365b33c6fb.mp3",
    provider: "ELEVENLABS",
  },
  {
    voiceId: "6WwXjDDEMyNmFG95zycZ",
    value: "6WwXjDDEMyNmFG95zycZ",
    name: "Eldrin",
    label: "Eldrin - Crisp British Baritone",
    gender: "male",
    age: "middle-aged",
    accent: "British",
    style: "raspy",
    useCase: "narrative_story",
    languageCode: "en",
    languageCodes: ["en", "hi", "sv", "no", "hr", "ms", "ro", "ta", "ar", "tr", "es", "de"],
    category: "high_quality",
    description: "Gritty mid range baritone with a modern British accent. Clear, controlled, and trustworthy for narration and explainers.",
    previewURL: "https://storage.googleapis.com/eleven-public-prod/database/workspace/1da06ea679a54975ad96a2221fe6530d/voices/6WwXjDDEMyNmFG95zycZ/RT3f2jFU3dCgQQwtz3dC.mp3",
    provider: "ELEVENLABS",
  },
  {
    voiceId: "dvbL7qkNGZY1IqPGZAjM",
    value: "dvbL7qkNGZY1IqPGZAjM",
    name: "Elowen",
    label: "Elowen - Upbeat Modern Narrator",
    gender: "female",
    age: "middle-aged",
    accent: "American",
    style: "casual",
    useCase: "conversational",
    languageCode: "en",
    languageCodes: ["en", "id", "el", "no", "ta", "uk", "cs", "hr", "it", "ko", "ar", "tr", "ru", "de", "pl", "pt"],
    category: "high_quality",
    description: "Bright, smooth female tone. Young and lively, with clear diction for modern narration and promos.",
    previewURL: "https://api.us.elevenlabs.io/v1/voices/dvbL7qkNGZY1IqPGZAjM/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJjdXN0b20iLCJ3b3Jrc3BhY2VfaWQiOiIxZGEwNmVhNjc5YTU0OTc1YWQ5NmEyMjIxZmU2NTMwZCIsImZpbGVuYW1lIjoibHdiVTFRZ0x1R1U3NWhvRG5WZFkubXAzIiwidGltZXN0YW1wIjoxNzkwMTU3NjAwMDAwMDAwfQ%3D%3D",
    provider: "ELEVENLABS",
  },
  {
    voiceId: "10NkTYmU7tSz3Kkl3Lex",
    value: "10NkTYmU7tSz3Kkl3Lex",
    name: "Kaelen",
    label: "Kaelen - Amateur Warrior",
    gender: "male",
    age: "middle-aged",
    accent: "American",
    style: "wise",
    useCase: "narrative_story",
    languageCode: "en",
    languageCodes: ["en"],
    category: "high_quality",
    description: "Rugged, gravelly male bass-baritone. Intense and textured, perfect for cinematic trailers or hardened character monologues.",
    previewURL: "https://storage.googleapis.com/eleven-public-prod/database/workspace/1da06ea679a54975ad96a2221fe6530d/voices/10NkTYmU7tSz3Kkl3Lex/Izw3uUEUt4DKcvYtVF5B.mp3",
    provider: "ELEVENLABS",
  },
  {
    voiceId: "ktkP7Nsj67dw2zcplQYt",
    value: "ktkP7Nsj67dw2zcplQYt",
    name: "Lawrence",
    label: "Lawrence - Bright and Informative",
    gender: "male",
    age: "young",
    accent: "American",
    style: "confident",
    useCase: "social_media",
    languageCode: "en",
    languageCodes: ["en"],
    category: "high_quality",
    description: "Crisp, energetic male with a resonant tone. Articulate and engaging for educational content and high-energy commercial voiceovers.",
    previewURL: "https://storage.googleapis.com/eleven-public-prod/database/workspace/1da06ea679a54975ad96a2221fe6530d/voices/ktkP7Nsj67dw2zcplQYt/HLqkY4HmHjsgYkZUS8Fj.mp3",
    provider: "ELEVENLABS",
  },
  {
    voiceId: "BFd5oBc2DDna33pSi4Gf",
    value: "BFd5oBc2DDna33pSi4Gf",
    name: "Alicia",
    label: "Alicia - Polished Global Anchor",
    gender: null,
    age: "middle-aged",
    accent: "British",
    style: "classy",
    useCase: "narrative_story",
    languageCode: "en",
    languageCodes: ["en"],
    category: "high_quality",
    description: "Authoritative, refined British female RP. Impeccable diction and a sophisticated tone ideal for corporate narration and prestige news.",
    previewURL: "https://storage.googleapis.com/eleven-public-prod/database/workspace/1da06ea679a54975ad96a2221fe6530d/voices/DNYvvkdiu5NYK2rSLwDL/58662aa8-3484-459c-9e79-31fe579b2045.mp3",
    provider: "ELEVENLABS",
  },
  {
    voiceId: "QtY3JBOUKEB5xzrRfOKc",
    value: "QtY3JBOUKEB5xzrRfOKc",
    name: "Maisie",
    label: "Maisie - Friendly Casual Neighbor",
    gender: "female",
    age: "young",
    accent: "American",
    style: "pleasant",
    useCase: "entertainment_tv",
    languageCode: "en",
    languageCodes: ["en", "it", "uk", "es", "el", "ko", "no", "sk", "tr", "vi", "cs", "fr", "hu", "ro", "ru", "de", "pt", "pl"],
    category: "high_quality",
    description: "Warm, approachable female alto. Bright and unpretentious for \"girl-next-door\" commercials and relatable social media content.",
    previewURL: "https://storage.googleapis.com/eleven-public-prod/database/workspace/1da06ea679a54975ad96a2221fe6530d/voices/QtY3JBOUKEB5xzrRfOKc/sxNrxFKYQqJM2twaupIl.mp3",
    provider: "ELEVENLABS",
  },
  {
    voiceId: "7QN34D2r3hCNwbOYIeK0",
    value: "7QN34D2r3hCNwbOYIeK0",
    name: "Warren",
    label: "Warren - Effortless and Cool",
    gender: "male",
    age: "young",
    accent: "American",
    style: "excited",
    useCase: "conversational",
    languageCode: "en",
    languageCodes: ["en"],
    category: "high_quality",
    description: "Smooth, laid-back male baritone. Relaxed pacing and a modern, conversational flow for lifestyle brands and authentic storytelling.",
    previewURL: "https://storage.googleapis.com/eleven-public-prod/database/workspace/1da06ea679a54975ad96a2221fe6530d/voices/7QN34D2r3hCNwbOYIeK0/63ac2ee7-8046-4b2f-bb6f-7c65437b7d9d.mp3",
    provider: "ELEVENLABS",
  },
  {
    voiceId: "g7LVvkPWALzPxOQbF6OE",
    value: "g7LVvkPWALzPxOQbF6OE",
    name: "Jade",
    label: "Jade - Upbeat and Natural",
    gender: "female",
    age: "young",
    accent: "American",
    style: "upbeat",
    useCase: "social_media",
    languageCode: "en",
    languageCodes: ["en"],
    category: "high_quality",
    description: "High-energy, unpredictable female voice. Features rapid-fire delivery and a playful, erratic cadence for \"Gen-Z\" marketing and avant-garde media.",
    previewURL: "https://storage.googleapis.com/eleven-public-prod/database/workspace/1da06ea679a54975ad96a2221fe6530d/voices/g7LVvkPWALzPxOQbF6OE/ZglHE6CY6Su9USd2h7sU.mp3",
    provider: "ELEVENLABS",
  },
  {
    voiceId: "AaOhDHYJ1XLZk74lXhdE",
    value: "AaOhDHYJ1XLZk74lXhdE",
    name: "Caleb",
    label: "Caleb - Trusted Guide",
    gender: "male",
    age: "young",
    accent: "American",
    style: "casual",
    useCase: "entertainment_tv",
    languageCode: "en",
    languageCodes: ["en"],
    category: "high_quality",
    description: "Down-to-earth with a slight smile in the tone. It’s a grounded, mid-range voice that works perfectly for \"slice of life\" stories or relatable brand messaging.",
    previewURL: "https://storage.googleapis.com/eleven-public-prod/database/workspace/1da06ea679a54975ad96a2221fe6530d/voices/AaOhDHYJ1XLZk74lXhdE/09516965-289e-4f78-9e36-569a22477d09.mp3",
    provider: "ELEVENLABS",
  },
  {
    voiceId: "8dEUmyPMdDdK91vboYih",
    value: "8dEUmyPMdDdK91vboYih",
    name: "Sawyer",
    label: "Sawyer - Midnight Storyteller",
    gender: "male",
    age: "middle-aged",
    accent: "American",
    style: "deep",
    useCase: "narrative_story",
    languageCode: "en",
    languageCodes: ["en"],
    category: "high_quality",
    description: "A rich, gravelly baritone with a steady pulse. Perfect for cinematic trailers, noir narrations, or premium luxury advertisements.",
    previewURL: "https://storage.googleapis.com/eleven-public-prod/database/workspace/1da06ea679a54975ad96a2221fe6530d/voices/8dEUmyPMdDdK91vboYih/YYGMnAuSXy7aGwkcMzM0.mp3",
    provider: "ELEVENLABS",
  },
  {
    voiceId: "fnYMz3F5gMEDGMWcH1ex",
    value: "fnYMz3F5gMEDGMWcH1ex",
    name: "Finley",
    label: "Finley - Articulate Anchor",
    gender: "male",
    age: "old",
    accent: "British",
    style: "deep",
    useCase: "narrative_story",
    languageCode: "en",
    languageCodes: ["en"],
    category: "high_quality",
    description: "Crisp, clear, and unflappable. This rhythmic British voice provides a sense of authority and flow for complex explainers.",
    previewURL: "https://storage.googleapis.com/eleven-public-prod/database/workspace/1da06ea679a54975ad96a2221fe6530d/voices/uxut3IsZzAX3ycGl84pJ/58652fb7-82bb-4523-8620-5f7325b27d01.mp3",
    provider: "ELEVENLABS",
  },
  {
    voiceId: "22N9cF8z0o7y23njdyaY",
    value: "22N9cF8z0o7y23njdyaY",
    name: "Florence",
    label: "Florence - Atmospheric Storyteller",
    gender: "female",
    age: "middle-aged",
    accent: "British",
    style: "gentle",
    useCase: "narrative_story",
    languageCode: "en",
    languageCodes: ["en"],
    category: "high_quality",
    description: "Sophisticated and lyrical, this voice flows like a steady stream. Perfect for immersive audiobooks or historical documentaries where the tone needs to be both grand and intimate.",
    previewURL: "https://api.us.elevenlabs.io/v1/voices/22N9cF8z0o7y23njdyaY/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJjdXN0b20iLCJ3b3Jrc3BhY2VfaWQiOiIxZGEwNmVhNjc5YTU0OTc1YWQ5NmEyMjIxZmU2NTMwZCIsImZpbGVuYW1lIjoiRjNzaE92TnhxaWRCOHBrZUdUWUsubXAzIiwidGltZXN0YW1wIjoxNzkwMTU3NjAwMDAwMDAwfQ%3D%3D",
    provider: "ELEVENLABS",
  },
  {
    voiceId: "FrS6cKLB1wg4WYgPa9GW",
    value: "FrS6cKLB1wg4WYgPa9GW",
    name: "Wyatt",
    label: "Wyatt - Seasoned Mentor",
    gender: "male",
    age: "middle-aged",
    accent: "American",
    style: "deep",
    useCase: "narrative_story",
    languageCode: "en",
    languageCodes: ["en"],
    category: "high_quality",
    description: "Measured and thoughtful, this voice carries the weight of experience. Ideal for long-form documentaries or insightful educational content.",
    previewURL: "https://storage.googleapis.com/eleven-public-prod/database/workspace/1da06ea679a54975ad96a2221fe6530d/voices/FrS6cKLB1wg4WYgPa9GW/401782f2-fb6e-46fb-b69b-e9c9530608ab.mp3",
    provider: "ELEVENLABS",
  },
];
